# Generated by Django 5.2.4 on 2025-09-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscribe_to_newsletter',
            field=models.BooleanField(default=True, verbose_name='Согласие на рассылку'),
        ),
    ]
