services:
  web:
    build: .
    image: web:1.0.0
    env_file:
      - .env
    depends_on:
        - db
        - redis

  db:
    image: postgres:16-bookworm
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_PORT=${DB_PORT}

  redis:
    image: redis:8.2-bookworm
    volumes:
      - redis_data:/data

volumes:
  redis_data:
  postgres_data: