# Generated by Django 5.2.4 on 2025-09-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('в наличии', 'в наличии'), ('нет в наличии', 'нет в наличии')], default='нет в наличии', max_length=100, verbose_name='Статус'),
        ),
    ]
