# Generated by Django 5.2.4 on 2025-09-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'в наличии'), (0, 'нет в наличии')], default=0, max_length=100, verbose_name='Статус'),
        ),
    ]
